services:
  raretide:
    container_name: server
    build:
      dockerfile: Dockerfile
    command: uvicorn app.main:app --port 8000 --host 0.0.0.0
    ports:
    - 8000:8000
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./db:/app/db
